### ISSUE TITLE
Investigate Contexts

### ISSUE THREAD

**Issue by firepear** [firepear/petrel#45]
https://blog.golang.org/context

People use this in HTTP land a lot. It might be useful here?

**Comment by clee** [comment]
Could be really useful. I've used contexts to attach useful metadata to HTTP responses before sending them (when the response is touched by multiple pieces of middleware, for example).

**Comment by firepear** [comment]
This has lingered, and lingered, and lingered. It seems clear that I'm not going to implement this right now. Closing 😄
